#define REDIS_GIT_SHA1 "26fa09bd"
#define REDIS_GIT_DIRTY "0"
#define REDIS_BUILD_ID "raspberrypi-1714470436"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
